apiVersion: v1
kind: Secret
metadata:
  name: {{ include "node-app.fullname" . }}-app-secret
  namespace: {{ include "node-app.namespace" .}}
type: Opaque
data: 
  SERVICE__SENSITIVE_DATA: {{ .Values.node.sensitiveData }}