apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "node-app.fullname" . }}
  namespace: {{ include "node-app.namespace" .}}
data: 
  SERVEICE__NONSENSITIVE_DATA: {{ .Values.node.nonSensitiveData }}