{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "node-app.fullname" . }}
  namespace: {{ include "node-app.namespace" .}}
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/issuer: {{ include "node-app.fullname" . }}-issuer
spec:
  tls:
  - hosts:
      - {{ .Values.ingress.hostname }}
    secretName: {{ .Values.ingress.hostname }}
  defaultBackend:
    service:
      name: {{ include "node-app.fullname" . }}
      port:
        number: {{ .Values.service.port }}
{{- end }}