apiVersion: v1
kind: Service
metadata:
  name: {{ include "node-app.fullname" . }}
  namespace: {{ include "node-app.namespace" .}}
  labels:
    {{- include "node-app.labels" . | nindent 4 }}
spec:
  ports:
  - port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.image.exposePort }}
  selector:
    {{- include "node-app.selectorLabels" . | nindent 6 }}
  type: {{ .Values.service.type }}